-- Seed Ariel street pronunciations (87 entries from data/ariel_streets.json).
-- Safe to re-run: ON CONFLICT updates phonetic_text + notes for existing originals.

insert into pronunciations (original_text, phonetic_text, notes) values
  ('הוורדים', 'הַוְּרָדִים', 'category:flowers; confidence:high'),
  ('יסמין', 'יַסְמִין', 'category:flowers; confidence:high'),
  ('כלנית', 'כַּלָּנִית', 'category:flowers; confidence:high'),
  ('כלניות', 'כַּלָּנִיּוֹת', 'category:flowers; confidence:high'),
  ('אירוס', 'אִירוּס', 'category:flowers; confidence:high'),
  ('נורית', 'נוּרִית', 'category:flowers; confidence:high'),
  ('נרקיס', 'נַרְקִיס', 'category:flowers; confidence:high'),
  ('סביון', 'סַבְיוֹן', 'category:flowers; confidence:high'),
  ('הסביונים', 'הַסַּבְיוֹנִים', 'category:flowers; confidence:high'),
  ('עירית', 'עִירִית', 'category:flowers; confidence:high'),
  ('חבצלת', 'חֲבַצֶּלֶת', 'category:flowers; confidence:high'),
  ('חצב', 'חָצָב', 'category:flowers; confidence:high'),
  ('חרצית', 'חַרְצִית', 'category:flowers; confidence:high'),
  ('רקפת', 'רַקֶּפֶת', 'category:flowers; confidence:high'),
  ('רותם', 'רֹתֶם', 'category:flowers; confidence:high'),
  ('הרדוף', 'הַרְדּוּף', 'category:flowers; confidence:high'),
  ('סיגלית', 'סִיגָלִית', 'category:flowers; confidence:high'),
  ('הדס', 'הֲדַס', 'category:flowers; confidence:high'),
  ('האלון', 'הָאַלּוֹן', 'category:trees; confidence:high'),
  ('הארז', 'הָאֶרֶז', 'category:trees; confidence:high'),
  ('הדקל', 'הַדֶּקֶל', 'category:trees; confidence:high'),
  ('הערבה', 'הָעֲרָבָה', 'category:trees; confidence:high'),
  ('השקד', 'הַשָּׁקֵד', 'category:trees; confidence:high'),
  ('השקמה', 'הַשִּׁקְמָה', 'category:trees; confidence:high'),
  ('הזית', 'הַזַּיִת', 'category:trees; confidence:high'),
  ('משעול הזית', 'מִשְׁעוֹל הַזַּיִת', 'category:trees; confidence:high'),
  ('תדהר', 'תִּדְהָר', 'category:trees; confidence:high'),
  ('האשל', 'הָאֶשֶׁל', 'category:trees; confidence:high'),
  ('הגלבוע', 'הַגִּלְבּוֹעַ', 'category:geography; confidence:high'),
  ('הגלעד', 'הַגִּלְעָד', 'category:geography; confidence:high'),
  ('הגליל', 'הַגָּלִיל', 'category:geography; confidence:high'),
  ('הנגב', 'הַנֶּגֶב', 'category:geography; confidence:high'),
  ('הבשן', 'הַבָּשָׁן', 'category:geography; confidence:high'),
  ('החרמון', 'הַחֶרְמוֹן', 'category:geography; confidence:high'),
  ('התבור', 'הַתָּבוֹר', 'category:geography; confidence:high'),
  ('הירדן', 'הַיַּרְדֵּן', 'category:geography; confidence:high'),
  ('מוריה', 'מוֹרִיָּה', 'category:geography; confidence:high'),
  ('רמת הגולן', 'רָמַת הַגּוֹלָן', 'category:geography; confidence:high'),
  ('שניר', 'שְׂנִיר', 'category:geography; confidence:high'),
  ('הכרמל', 'הַכַּרְמֶל', 'category:geography; confidence:high'),
  ('בית לחם', 'בֵּית לֶחֶם', 'category:biblical_places; confidence:high'),
  ('חברון', 'חֶבְרוֹן', 'category:biblical_places; confidence:high'),
  ('יודפת', 'יוֹדְפַת', 'category:biblical_places; confidence:high'),
  ('יהודה', 'יְהוּדָה', 'category:biblical_places; confidence:high'),
  ('מואב', 'מוֹאָב', 'category:biblical_places; confidence:high'),
  ('אפרתה', 'אֶפְרָתָה', 'category:biblical_places; confidence:high'),
  ('אילות', 'אֵילוֹת', 'category:biblical_places; confidence:high'),
  ('ציון', 'צִיּוֹן', 'category:biblical_places; confidence:high'),
  ('ימית', 'יָמִית', 'category:biblical_places; confidence:high'),
  ('שער הגיא', 'שַׁעַר הַגַּיְא', 'category:biblical_places; confidence:high'),
  ('השומרון', 'הַשּׁוֹמְרוֹן', 'category:biblical_places; confidence:high'),
  ('עפרון', 'עֶפְרוֹן', 'category:biblical_places; confidence:medium'),
  ('מפרץ אילת', 'מִפְרַץ אֵילַת', 'category:biblical_places; confidence:high'),
  ('מפרץ שלמה', 'מִפְרַץ שְׁלֹמֹה', 'category:biblical_places; confidence:high'),
  ('גילה', 'גִּילֹה', 'category:biblical_places; confidence:medium'),
  ('אבנר', 'אַבְנֵר', 'category:heroes; confidence:high'),
  ('גדעון', 'גִּדְעוֹן', 'category:heroes; confidence:high'),
  ('יפתח', 'יִפְתָּח', 'category:heroes; confidence:high'),
  ('יואב', 'יוֹאָב', 'category:heroes; confidence:high'),
  ('ברק', 'בָּרָק', 'category:heroes; confidence:high'),
  ('אורי בראון', 'אוּרִי בְּרָאוּן', 'category:heroes; confidence:high'),
  ('מבצע דני', 'מִבְצָע דָּנִי', 'category:operations; confidence:high'),
  ('מבצע עובדה', 'מִבְצַע עוֹבְדָה', 'category:operations; confidence:high'),
  ('מבצע חירם', 'מִבְצַע חִירָם', 'category:operations; confidence:high'),
  ('מבצע קדש', 'מִבְצַע קָדֵשׁ', 'category:operations; confidence:high'),
  ('מבצע הראל', 'מִבְצַע הָרֵאל', 'category:operations; confidence:high'),
  ('דרך הציונות', 'דֶּרֶךְ הַצִּיּוֹנוּת', 'category:zionism; confidence:high'),
  ('ששת הימים', 'שֵׁשֶׁת הַיָּמִים', 'category:zionism; confidence:high'),
  ('ההגנה', 'הַהֲגָנָה', 'category:zionism; confidence:high'),
  ('האצ״ל', 'הָאֶצַ״ל', 'category:zionism; confidence:high'),
  ('הנחשונים', 'הַנַּחְשׁוֹנִים', 'category:zionism; confidence:high'),
  ('דרך הנחשונים', 'דֶּרֶךְ הַנַּחְשׁוֹנִים', 'category:zionism; confidence:high'),
  ('הקוממיות', 'הַקּוֹמְמִיּוּת', 'category:zionism; confidence:medium'),
  ('העצמאות', 'הָעַצְמָאוּת', 'category:zionism; confidence:high'),
  ('רון נחמן', 'רוֹן נַחְמָן', 'category:zionism; confidence:high'),
  ('צה״ל', 'צַהַ״ל', 'category:zionism; confidence:high'),
  ('הפסגה', 'הַפִּסְגָּה', 'category:descriptive; confidence:high'),
  ('הגנים', 'הַגַּנִּים', 'category:descriptive; confidence:high'),
  ('נווה שאנן', 'נְוֵה שַׁאֲנָן', 'category:descriptive; confidence:high'),
  ('כלילת יופי', 'כְּלִילַת יֹפִי', 'category:descriptive; confidence:high'),
  ('מעלה הגבעה', 'מַעֲלֵה הַגִּבְעָה', 'category:descriptive; confidence:high'),
  ('יפה נוף', 'יְפֵה נוֹף', 'category:descriptive; confidence:high'),
  ('עיר היונה', 'עִיר הַיּוֹנָה', 'category:descriptive; confidence:high'),
  ('מבוא חמה', 'מְבוֹא חַמָּה', 'category:descriptive; confidence:high'),
  ('חופית', 'חוֹפִית', 'category:descriptive; confidence:high'),
  ('אזור תעשייה מערב', 'אֵזוֹר תַּעֲשִׂיָּה מַעֲרָב', 'category:descriptive; confidence:high'),
  ('מכללת אריאל', 'מִכְלֶלֶת אֲרִיאֵל', 'category:descriptive; confidence:high')
on conflict (original_text) do update
  set phonetic_text = excluded.phonetic_text,
      notes = excluded.notes,
      updated_at = now();
